# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrez_id', models.IntegerField(default=0)),
                ('gene_symbol', models.CharField(max_length=10)),
                ('gene_name', models.CharField(max_length=200)),
            ],
        ),
    ]
